paths:
  /api/v1/symbols_structure/characters/{id}/:
    get:
      operationId: characters-detail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
      tags:
        - Symbols Structure
components:
  schemas:
    Character:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
tags:
  - name: Symbols Structure
