name: archetype
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  api:
    image: ghcr.io/archetype-pal/backend:latest
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    command: python manage.py runserver 0.0.0.0:80 --nostatic
    env_file: ${API_ENV_FILE:-config/.env}
    ports:
      - "8000:80"
    volumes:
      - .:/src
    depends_on:
      - postgres
  image_server:
    image: daschswiss/sipi
    ports:
      - 1024:1024
    volumes:
      - ./storage/media:/sipi/images

volumes:
  postgres:
