name: archetype
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    # Production: hide these env vars on production by using a .env file
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  api:
    image: ghcr.io/archetype-pal/archetype3:latest
    # Production: remove the following line
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    # Production: remove the following line
    command: python manage.py runserver 0.0.0.0:80 --nostatic
    # Production: change `config/.env` to the location of your .env file
    # Note: don't just use `.env` as it has special meaning in docker-compose
    env_file: ${API_ENV_FILE:-config/.env}
    # production: You might want to change the destination port to 80 if you don't have a reverse proxy.
    ports:
      - "8000:80"
    volumes:
      # Production: remove the following line
      - .:/src
      # Production: uncomment the following line
      # don't forget to create an empty storage folder in the root of your project
      # - ./storage:/src/storage
    depends_on:
      - postgres
  image_server:
    image: daschswiss/sipi
    ports:
      - 1024:1024
    volumes:
      - ./storage/media:/sipi/images

volumes:
  postgres:
