paths:
  /api/v1/scribes/{id}/:
    get:
      operationId: scribes-details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scribe'
      tags:
        - scribes
components:
  schemas:
    Scribe:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        period:
          type: string
        scriptorium:
          type: string
        script:
          type: object
          properties:
            name:
              type: string
        hands:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              script:
                type: object
                properties:
                  name:
                    type: string
        
tags:
  - name: scribes
